### ISSUE TITLE
NotificationSubscription.Context.MO does not work as intended

### ISSUE THREAD

**Issue by definitelyNotACatfish** [SoftwareAG/cumulocity-clients-dotnet#11]
Hi,

when I try to subscribe using CreateSubscription from "NotificationSubscription.cs", the generated "NotificationSubscription" body as input parameter looks like this:
```json
{
  "context": "MO",
  "source": {
    "id": "wonderfulID"
  },
  "subscription": "Subscription",
  "subscriptionFilter": {
    "api": [
      "events"
    ],
    "typeFilter": "c8y_LoriotUplinkRequest"
  }
}
```

It does not correctly convert the context, it seems that it does not use the "[EnumMember(Value = "mo")]" of enum "Context".
Anyway, when I change the enum "MO" to "mo" in "NotificationSubscription.cs"
```C#
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum Context 
{
	[EnumMember(Value = "mo")]
	mo,
	[EnumMember(Value = "tenant")]
	tenant
}
```
 it works:
```json
{
  "context": "mo",
  "source": {
    "id": "wonderfulID"
  },
  "subscription": "Subscription",
  "subscriptionFilter": {
    "api": [
      "events"
    ],
    "typeFilter": "c8y_LoriotUplinkRequest"
  }
}
```

**Comment by joerghartmann** [comment]
`EnumMember` annotation is not taken into account. Simple repro:

```csharp
var n = new NotificationSubscription();
n.PContext = NotificationSubscription.Context.MO;
Console.WriteLine(n.ToString());
```

produces

```json
{   
    "context": "MO" 
}
```

but must be (as described in `EnumMember`)

```json
{   
    "context": "mo" 
}
```

**Comment by joerghartmann** [comment]
Works with Newtonsoft.Json. However, we won't like to add this dependency in this repository.

**Comment by definitelyNotACatfish** [comment]
Ok, I will test it

**Comment by joerghartmann** [comment]
We've written a custom converter. Seems that the `System.Runtime.Serialization` attributes are ignored by `System.Text.Json`.

Let you know once it's in here.

**Comment by definitelyNotACatfish** [comment]
Great, thanks! :)

**Comment by joerghartmann** [comment]
@definitelyNotACatfish Please see the latest commit. We've added a converter factory for enums taken the serialised name into account.
