### ISSUE TITLE
Main branch not buildable

### ISSUE THREAD

**Issue by definitelyNotACatfish** [SoftwareAG/cumulocity-clients-dotnet#13]
Currently (29.11.2022), the main branch is not build able by default. I had to comment out 2 Files:
- IInventoryApi.cs
- InventoryApi.cs

I didn't check what the problem excaclty is, because I don't need these files, but can you please check?

**Comment by joerghartmann** [comment]
Sorry for the late reply. You can contact me directly via mail: joerg.hartmann@softwareag.com. 

We recognized an issue during a merge. Both files are outdated and have been removed.
