### ISSUE TITLE
No method for generating an access token 

### ISSUE THREAD

**Issue by definitelyNotACatfish** [SoftwareAG/cumulocity-clients-dotnet#14]
When I want to generate an access token, to access the inventory, I can't use the LoginTokenAPI. The class does not contain any method got generate the token. Is the class obsolete?

**Comment by joerghartmann** [comment]
@definitelyNotACatfish Could you please try the follwing:

https://cumulocity.com/api/10.13.0/#operation/postLoginFormBody. Have a look at `LoginTokensApi`.

**Comment by definitelyNotACatfish** [comment]
@joerghartmann thanks I will take a look. Anyway I didn't need it at all, I've seen that I can access the inventory with BASIC auth 😄 . Issue can be closed from my side.

**Comment by joerghartmann** [comment]
Great :)
I'll close it and have a look at the other issues as well. Just write me a message/mail if you have urgent needs or need assistance.
