### ISSUE TITLE
[JsonPropertyName("api")] in NotificationSubscription.cs not correct

### ISSUE THREAD

**Issue by definitelyNotACatfish** [SoftwareAG/cumulocity-clients-dotnet#18]
Hi,
 the JPN of Api is not correct, it has to be:
```c#
[JsonPropertyName("apis")]
public List<string>? Api { get; set; }
```

There is also a bug in the docu, which I issed there.

Kind Regards

**Comment by joerghartmann** [comment]
Hey, 

ya thats true. Issue has been addressed already and I will update the repo soon.

**Comment by joerghartmann** [comment]
Has been resolved with the latest merge.
