### ISSUE TITLE
base address has slash appendix

### ISSUE THREAD

**Issue by PeterGeorgs** [SoftwareAG/cumulocity-clients-dotnet#4]
Urls are build e.g. this way: 
`var uriBuilder = new UriBuilder(new Uri($"{client?.BaseAddress?.AbsoluteUri}/identity/externalIds/{type}/{externalId}"));`
but the client?.BaseAddress?.AbsoluteUri has already  a slash appendix.

The uri looks like this: 
https://example.de:443//identity/externalIds/example_type/1

Note the doubly slashes

**Comment by joerghartmann** [comment]
@PeterGeorgs This has been addressed recently. Code in the `main` branch shows the changes. I already did comment your pull request.
