### ISSUE TITLE
Add support for setting processing modes (e.g. transient, quiescent)

### ISSUE THREAD

**Issue by reubenmiller** [SoftwareAG/cumulocity-clients-dotnet#9]
Add support for setting the Cumulocity processing mode on all PUT, POST and DELETE requests.

This is documented in the [general section of the docs](https://cumulocity.com/api/10.13.0/#section/REST-implementation/HTTP-usage ) under "Processing mode".

**Use-case**

In order to save costs, some measurements are pushed to the platform using the TRANSIENT processing mode so that the measurements are visible in the UI however they are not persisted in the platform. 

**Feature details**

* Ability to set it on a per-request basis (using default headers would add this mode for all requests, which is often not desired)

**Comment by joerghartmann** [comment]
@reubenmiller I think the header param has to be added in the OpenAPI doc. Just forwarded this request to the doc team.

**Comment by reubenmiller** [comment]
Though having a custom way to add some headers to requests might be useful, however in the meantime we will have to use two different client instances (one with default headers to control the processing mode to transient, and the other to handle other requests)

**Comment by joerghartmann** [comment]
@reubenmiller I'll close it. The param is now added to each PUT/POST/DELETE request.
